version: 2

project_name: rssaurus

before:
  hooks:
    - go mod tidy

builds:
  - id: rssaurus
    main: ./cmd/rssaurus
    binary: rssaurus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

release:
  draft: false

brews:
  - name: rssaurus
    description: "RSSaurus command-line client"
    homepage: "https://rssaurus.com"
    license: "MIT"

    # Where to publish the formula
    repository:
      owner: RSSaurus
      name: tap

    directory: Formula

    # The executable name
    install: |
      bin.install "rssaurus"

    # Make formula updates deterministic
    commit_author:
      name: RSSaurus Bot
      email: bot@rssaurus.com

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
